### ISSUE TITLE
Games page refinements

### ISSUE THREAD

**Issue by pchote** [Fauntleroy/openra-web#5]
This page is generally excellent. Just a couple of thoughts:

* The "Showing X servers hosting Y players." line still doesn't seem to be counting spectators in the player count
* Showing the mod icons at 32px looks really fuzzy on hidpi displays. Can we keep these as 16px like before, or otherwise use `image-rendering: crisp-edges` to preserve the contrast?
* It would be great if we could display the "Requires OpenRA forum account" glyph if `"authentication":true` and use the same padlock glyph as the ingame browser for passworded games for consistency. The svg shapes can be pulled from https://github.com/OpenRA/ArtSrc/blob/master/ra/glyphs.svg
* It would be great if we could support the new [spawn disabling](https://github.com/OpenRA/OpenRA/pull/18425) feature in the tooltip. A `"disabled_spawn_points":"1,3"` key in the server json means that spawn numbers 1 and 3 should be displayed as disabled (remove the number and put a cross through the background).
* Is there any reason why the player activity graph isn't the same width as the games list?

**Comment by takempf** [comment]
- Added spectators to all player count totals
- Elected to use `crisp-edges` / `pixelate` on the mod icons. At 16px the icons are simply too small to be readable at all. In an ideal future, mod icons can be retrieved at much higher resolutions :/ 
- I've taken the account icon and added it to any game listing with `authenticated` set
- I've added the code to handle `disabled_spawn_points`. It should work as soon as the API includes this feature.
- There is a reason, but it's simply because the list changed width and the stats did not. I've modified all stats charts to be the same large size as the games list.

<img width="101" alt="Screen Shot 2020-12-12 at 10 07 20 PM" src="https://user-images.githubusercontent.com/507047/102005369-29ab8180-3ccd-11eb-8cb7-d93d2d5637fc.png">
<img width="286" alt="image" src="https://user-images.githubusercontent.com/507047/102005382-3f20ab80-3ccd-11eb-92a4-2e2d8721cd48.png">

https://github.com/Fauntleroy/openra-web/commit/1910f24dc0d489b43dc049aeeda1d9838c0821dd
https://github.com/Fauntleroy/openra-web/commit/b49969c3fda5aa22d5ead5a1025d0267cd3ae410
